name: asx
description: asx is a lightweight library for parsing asx documents from document string.
version: 1.0.3
homepage: https://github.com/Andromo-App-Maker/asx

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  xml: ^5.1.2
  equatable: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
